const products=[
    {
        id: 1,
        idCat: "platoFuerte",
        name: "Pasta fresca con langostinos",
        description: "Cintas de harina de semola envuelta en vegetales frescos con langostinos salteados Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 60.5,
        discount: true,
        discountAmount: 20,
        img: "fNoodles.png",
        reco: true
    },
    {
        id: 2,
        idCat: "platoFuerte",
        name: "Barbacoa con ensalada gourmet",
        description: "Barbacoa con ensalada gourmet de vegetales orgánicos Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 55.53,
        discount: true,
        discountAmount: 12,
        img: "fBarbacoaEnsalada.png",
        reco: false
    },
    {
        id: 3,
        idCat: "platoFuerte",
        name: "Ribs de cerdo",
        description: "Costillas de cerdo en salsa BBQ y salsa de la casa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 45.23,
        discount: false,
        discountAmount: 0,
        img: "fCostillas.png",
        reco: true
    },
    {
        id: 4,
        idCat: "platoFuerte",
        name: "Falafel vegetariano con hummus",
        description: "Falafel con hummus y vegetales frescos Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 54.76,
        discount: true,
        discountAmount: 50,
        img: "fFalafelHummus.png",
        reco: false
    },
    {
        id: 5,
        idCat: "platoFuerte",
        name: "Milanesa con vegetales",
        description: "Milanesa en salsa BBQ con vegetales Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 53.65,
        discount: false,
        discountAmount: 0,
        img: "fMilanesaVegetales.png",
        reco: true
    },
    {
        id: 6,
        idCat: "platoFuerte",
        name: "Paella mediterránea",
        description: "Paella de mariscos Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 73.33,
        discount: true,
        discountAmount: 10,
        img: "fPaellaMediterranea.png",
        reco: false
    },
    {
        id: 7,
        idCat: "platoFuerte",
        name: "Pollo frito con papas rústicas",
        description: "Pollo frito con papas rústicas y ensalada Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 53.99,
        discount: false,
        discountAmount: 0,
        img: "fPolloFritoVegetales.png",
        reco: true
    },
    {
        id: 8,
        idCat: "platoFuerte",
        name: "Salmón con vegetales frescos",
        description: "Salmón ahumado con vegetales frescos Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 67.98,
        discount: true,
        discountAmount: 20,
        img: "fSalmonVegetales.png",
        reco: false
    },
    {
        id: 9,
        idCat: "platoFuerte",
        name: "Solomito con papas rústicas",
        description: "Solomito con papas rústicas y ensalada primavera Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 57.78,
        discount: false,
        discountAmount: 0,
        img: "fSolomito.png",
        reco: true
    },
    {
        id: 10,
        idCat: "bebida",
        name: "Coca-Cola 2.25L",
        description: "Coca-Cola 2.25L Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 10.65,
        discount: false,
        discountAmount: 0,
        img: "fCocacola.png",
        reco: false
    },
    {
        id: 11,
        idCat: "bebida",
        name: "Agua sin gas",
        description: "Agua en botella sin gas Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 4.20,
        discount: false,
        discountAmount: 0,
        img: "fAgua.png",
        reco: false
    },
    {
        id: 12,
        idCat: "bebida",
        name: "Coctel de vodka y kiwi",
        description: "Coctel de vodka con trozos de kiwi Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 12.75,
        discount: false,
        discountAmount: 0,
        img: "bCoctelVodkaKiwi.png",
        reco: false
    },
    {
        id: 13,
        idCat: "bebida",
        name: "Jugo de naranja",
        description: "Jugo natural de naranja sin azúcar Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 7.5,
        discount: false,
        discountAmount: 0,
        img: "bJugoNaranja.png",
        reco: false
    },
    {
        id: 14,
        idCat: "bebida",
        name: "Sangría de frutos rojos",
        description: "Sangría con variedad de frutos rojos en trozos Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 11.75,
        discount: false,
        discountAmount: 0,
        img: "bSangria.png",
        reco: false
    },
    {
        id: 15,
        idCat: "entrada",
        name: "Bruschettas con salsa artesanal de tomate",
        description: "Bruschettas con especias y salsa artesanal de tomate Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 11.75,
        discount: false,
        discountAmount: 0,
        img: "eBruschettasSalsaTomate.png",
        reco: false
    },
    {
        id: 16,
        idCat: "entrada",
        name: "Crema de champiñones",
        description: "Crema de champiñones Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 12.5,
        discount: false,
        discountAmount: 0,
        img: "eCremaChampinones.png",
        reco: false
    },
    {
        id: 17,
        idCat: "entrada",
        name: "Crema de tomate",
        description: "Crema de tomate Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 12.5,
        discount: false,
        discountAmount: 0,
        img: "eCremaTomate.png",
        reco: false
    },
    {
        id: 18,
        idCat: "entrada",
        name: "Crema de verduras",
        description: "Crema de verduras Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 12.5,
        discount: false,
        discountAmount: 0,
        img: "eCremaVerduras.png",
        reco: false
    },
    {
        id: 19,
        idCat: "entrada",
        name: "Dips con salsa de la casa",
        description: "Dips con salsa de la casa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 13.75,
        discount: false,
        discountAmount: 0,
        img: "eDipsSalsaCasa.png",
        reco: false
    },
    {
        id: 20,
        idCat: "entrada",
        name: "Ensalada Cesar",
        description: "Ensalada Cesar con vinagreta de tu elección Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 10.75,
        discount: false,
        discountAmount: 0,
        img: "eEnsaladaCesar.png",
        reco: false
    },
    {
        id: 21,
        idCat: "entrada",
        name: "Nachos con guacamole",
        description: "Nachos con guacamole Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 11.25,
        discount: false,
        discountAmount: 0,
        img: "eNachosGuacamole.png",
        reco: false
    },
    {
        id: 22,
        idCat: "postre",
        name: "Canasta de helado",
        description: "Canasta de helado de tu elección Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 13.25,
        discount: false,
        discountAmount: 0,
        img: "pCanastaHelado.png",
        reco: false
    },
    {
        id: 23,
        idCat: "postre",
        name: "Cheesecake de frutos rojos",
        description: "Cheesecake de frutos rojos Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 13.25,
        discount: false,
        discountAmount: 0,
        img: "pCheeseCakeFrutosRojos.png",
        reco: false
    },
    {
        id: 24,
        idCat: "postre",
        name: "Helado de tiramissú",
        description: "Helado de tiramissú con salsa de arequipe Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 13.25,
        discount: false,
        discountAmount: 0,
        img: "pHeladoTiramissu.png",
        reco: false
    },
    {
        id: 25,
        idCat: "postre",
        name: "Tarta de chocolate",
        description: "Tarta de chocolate Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 13.25,
        discount: false,
        discountAmount: 0,
        img: "pTartaChocolate.png",
        reco: false
    },
    {
        id: 26,
        idCat: "postre",
        name: "Brownie con arequipe",
        description: "Brownie con arequipe Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 13.25,
        discount: false,
        discountAmount: 0,
        img: "pTortaChocolate.png",
        reco: false
    },
    {
        id: 27,
        idCat: "postre",
        name: "Torta de vainilla con chocolate",
        description: "Torta de vainilla con chocolate Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 13.25,
        discount: false,
        discountAmount: 0,
        img: "pTortaVainillaChocolate.png",
        reco: false
    },
    {
        id: 28,
        idCat: "postre",
        name: "Waffle con helado",
        description: "Waffle con helado Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus ut metus faucibus hendrerit. Etiam sem dui, dignissim eget ullamcorper a, egestas sed felis. Vivamus sagittis volutpat neque, sed porta orci rutrum at. Fusce tempor posuere erat et blandit. Mauris ac pretium risus. Morbi eu tristique augue, ut sollicitudin tellus. Donec porttitor dui felis, a ultrices ante maximus at. Etiam vulputate, mauris quis accumsan placerat, nunc mi viverra diam, a sagittis turpis ipsum id magna. Vestibulum pellentesque urna lorem, in varius orci tincidunt at. Sed accumsan, mauris ut mollis lacinia, erat enim porttitor purus, in congue lorem purus nec risus. Suspendisse rhoncus lectus vitae blandit placerat. Aliquam posuere id nibh quis semper.",
        price: 13.25,
        discount: false,
        discountAmount: 0,
        img: "pWaffleHelado.png",
        reco: false
    }
]

module.exports = products;